name: Security audit
on:
  push:
    branches:
      - master
    paths: 
      - '.github/workflows/audit-check.yml'
      - '**/Cargo.toml'
      - '**/Cargo.toml'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}