name: Cargo Audit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install dependencies
      run: cargo build

    - name: Run cargo audit
      run: |
        cargo audit --json > audit_results.json
        cargo audit --json | cargo-audit-sarif > results.sarif || echo "Failed to convert audit results to SARIF format."

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif