name: Cargo Tarpaulin

on:
  push:
    branches:
      - master
  pull_request:
    
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: rust-lang/rustup@v1
        with:
          profile: minimal
          rust-version: stable

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run tests with coverage
        run: cargo tarpaulin --out Html